<?xml version="1.0"?>
<robot name="depth_cam"
  xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:macro name="depth_cam" params="name parent xyz rpy">

    <xacro:property name="r200_cam_color_px" value="0.005"/>
    <xacro:property name="r200_cam_color_py" value="0.018"/>
    <xacro:property name="r200_cam_color_pz" value="0.013"/>
    <xacro:property name="r200_cam_depth_offset" value="0.01"/>
    <xacro:arg name="camera_visual" default="false"/>

    <joint name="base_${name}_joint" type="fixed">
      <origin xyz="${xyz}" rpy="${rpy}" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
        <geometry>
          <mesh filename="package://urdf_basic_shapes/meshes/intel_d435.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
        <geometry>
          <box size="0.012 0.132 0.020"/>
        </geometry>
      </collision>
    </link>


    <joint name="${name}_color_joint" type="fixed">
      <origin xyz="${r200_cam_color_px} ${r200_cam_color_py} ${r200_cam_color_pz}" rpy="0 0 0"/>
      <parent link="${name}_link"/>
      <child link="${name}_color_frame"/>
    </joint>
    <link name="${name}_color_frame"/>

    <joint name="${name}_color_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
      <parent link="${name}_color_frame"/>
      <child link="${name}_color_optical_frame"/>
    </joint>
    <link name="${name}_color_optical_frame"/>

    <joint name="${name}_depth_joint" type="fixed">
      <origin xyz="${r200_cam_color_px} ${r200_cam_color_py + r200_cam_depth_offset} ${r200_cam_color_pz}" rpy="0 0 0"/>

      <parent link="${name}_link"/>
      <child link="${name}_depth_frame"/>
    </joint>
    <link name="${name}_depth_frame"/>

    <joint name="${name}_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
      <parent link="${name}_depth_frame"/>
      <child link="${name}_depth_optical_frame"/>
    </joint>
    <link name="${name}_depth_optical_frame"/>


    <gazebo reference="${name}_color_frame">
      <sensor type="depth" name="realsense_R200">

        <always_on>true</always_on>
        <visualize>$(arg camera_visual)</visualize>
        <camera>
          <horizontal_fov>1.3439</horizontal_fov>
          <image>
            <width>1920</width>
            <height>1080</height>
            <format>R8G8B8</format>
          </image>
          <depth_camera></depth_camera>
          <clip>
            <near>0.03</near>
            <far>100</far>
          </clip>
        </camera>
        <plugin name="${name}_controller" filename="libgazebo_ros_openni_kinect.so">
          <baseline>0.2</baseline>
          <alwaysOn>true</alwaysOn>
          <updateRate>30.0</updateRate>
          <cameraName>${name}</cameraName>
          <frameName>${name}_depth_optical_frame</frameName>
          <imageTopicName>color/image_raw</imageTopicName>
          <depthImageTopicName>depth/image_raw</depthImageTopicName>
          <pointCloudTopicName>depth/color/points</pointCloudTopicName>
          <cameraInfoTopicName>color/camera_info</cameraInfoTopicName>
          <depthImageCameraInfoTopicName>depth/${name}_info</depthImageCameraInfoTopicName>
          <pointCloudCutoff>0.4</pointCloudCutoff>
          <hackBaseline>0.07</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>

          <CxPrime>0.0</CxPrime>
          <Cx>0.0</Cx>
          <Cy>0.0</Cy>
          <focalLength>0</focalLength>
          <hackBaseline>0</hackBaseline>
        </plugin>
      </sensor>
    </gazebo>

  </xacro:macro>
</robot>
